In [4]:
import sqlite3

conn = sqlite3.connect("task2_database.db")

print("SQLite database created successfully!")

SQLite database created successfully!

In [5]:
import sqlite3

print(sqlite3.sqlite_version)

3.51.0

In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("cleaned_dataset.csv")

In [8]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9784,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9785,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9786,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9787,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9788,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [9]:
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9784    False
9785    False
9786    False
9787    False
9788    False
Length: 9789, dtype: bool

In [11]:
df.shape

(9789, 18)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9789 entries, 0 to 9788
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9789 non-null   int64
 1   Order ID       9789 non-null   object
 2   Order Date     9789 non-null   object
 3   Ship Date      9789 non-null   object
 4   Ship Mode      9789 non-null   object
 5   Customer ID    9789 non-null   object
 6   Customer Name  9789 non-null   object
 7   Segment        9789 non-null   object
 8   Country        9789 non-null   object
 9   City           9789 non-null   object
 10  State          9789 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9789 non-null   object
 13  Product ID     9789 non-null   object
 14  Category       9789 non-null   object
 15  Sub-Category   9789 non-null   object
 16  Product Name   9789 non-null   object
 17  Sales          9789 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [13]:
conn = sqlite3.connect("task2_database.db")

print("Database connected successfully!")

Database connected successfully!

In [14]:
df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

9789

In [15]:
query = "SELECT * FROM sales LIMIT 5;"

result = pd.read_sql_query(query, conn)

result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [16]:
##WHERE CONDITION
query = """
SELECT *
FROM sales
WHERE Sales > 1000;
"""

pd.read_sql_query(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,11,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184
1,25,CA-2016-106320,25/09/2016,30/09/2016,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057.0,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630
2,28,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430
3,36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
4,55,CA-2017-105816,11/12/2017,17/12/2017,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024.0,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,9674,CA-2017-114867,23/12/2017,28/12/2017,Standard Class,FM-14290,Frank Merwin,Home Office,United States,Philadelphia,Pennsylvania,19143.0,East,TEC-PH-10002645,Technology,Phones,LG G2,1499.970
455,9713,CA-2015-114251,05/11/2015,10/11/2015,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Philadelphia,Pennsylvania,19143.0,East,OFF-ST-10003716,Office Supplies,Storage,Tennsco Double-Tier Lockers,1080.096
456,9760,CA-2017-146913,31/10/2017,05/11/2017,Standard Class,SF-20965,Sylvia Foulston,Corporate,United States,San Francisco,California,94109.0,West,FUR-CH-10001854,Furniture,Chairs,Office Star - Professional Matrix Back Chair w...,1403.920
457,9775,CA-2015-169019,26/07/2015,30/07/2015,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,Texas,78207.0,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,2177.584
458,9788,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-BO-10001811,Furniture,Bookcases,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust...",1023.332

## ORDER BY

In [17]:
query = """ 
SELECT *
FROM sales 
ORDER BY Sales DESC;
""" 
pd.read_sql_query(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,2698,CA-2015-145317,18/03/2015,23/03/2015,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480
1,6827,CA-2017-118689,02/10/2017,09/10/2017,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950
2,8154,CA-2018-140151,23/03/2018,25/03/2018,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960
3,2624,CA-2018-127180,22/10/2018,24/10/2018,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968
4,4191,CA-2018-166709,17/11/2018,22/11/2018,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9784,2107,US-2015-152723,26/09/2015,26/09/2015,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,Texas,75150.0,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876
9785,4712,CA-2015-112403,31/03/2015,31/03/2015,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,19120.0,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852
9786,8659,CA-2017-168361,21/06/2017,25/06/2017,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,Illinois,60623.0,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836
9787,9293,CA-2018-124114,02/03/2018,02/03/2018,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,Texas,76706.0,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556
9788,4102,US-2018-102288,19/06/2018,23/06/2018,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,Texas,77095.0,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444

##LIMIT

In [18]:
query = """ 
SELECT *
FROM sales
LIMIT 5;
"""
pd.read_sql_query(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

### GROUPBY

In [19]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name";
"""
result =pd.read_sql_query(query, conn)
result

                                           Product Name  Total_Sales
0     "While you Were Out" Message Book, One Form pe...       25.228
1              #10 Gummed Flap White Envelopes, 100/Box       41.300
2                         #10 Self-Seal White Envelopes      108.682
3            #10 White Business Envelopes,4 1/8 x 9 1/2      379.214
4               #10- 4 1/8" x 9 1/2" Recycled Envelopes      286.672
...                                                 ...          ...
1843  iKross Bluetooth Portable Keyboard + Cell Phon...      477.660
1844                         iOttie HLCRIO102 Car Mount      215.892
1845                                iOttie XL Car Mount      223.888
1846  invisibleSHIELD by ZAGG Smudge-Free Screen Pro...      442.554
1847                 netTALK DUO VoIP Telephone Service     1112.788

[1848 rows x 2 columns]

### HAVING

In [20]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name"
HAVING SUM(Sales) > 5000
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

                                          Product Name  Total_Sales
0                Canon imageCLASS 2200 Advanced Copier    61599.824
1    Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2    Cisco TelePresence System EX90 Videoconferenci...    22638.480
3         HON 5400 Series Task Chairs for Big and Tall    21870.576
4           GBC DocuBind TL300 Electric Binding System    19823.479
..                                                 ...          ...
99         Lifetime Advantage Folding Chairs, 4/Carton     5212.112
100  Atlantic Metals Mobile 4-Shelf Bookcases, Cust...     5184.081
101  Razer Tiamat Over Ear 7.1 Surround Sound PC Ga...     5119.744
102  Chromcraft 48" x 96" Racetrack Double Pedestal...     5098.176
103     Hoover Shoulder Vac Commercial Portable Vacuum     5009.480

[104 rows x 2 columns]

#JOINS

In [21]:
customers = df[
    ["Customer ID", "Customer Name", "Segment"]
].drop_duplicates()

customers.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

793

In [22]:
orders = df[
    ["Order ID", "Customer ID", "Sales", "Category"]
]

orders.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

9789

## joining_both tables

In [23]:
query = """
SELECT
    c."Customer Name",
    c.Segment,
    o."Order ID",
    o.Sales,
    o.Category
FROM customers c
JOIN orders o
ON c."Customer ID" = o."Customer ID";
"""

pd.read_sql_query(query, conn).head(10)

     Customer Name    Segment        Order ID    Sales         Category
0      Claire Gute   Consumer  CA-2017-152156  261.960        Furniture
1      Claire Gute   Consumer  CA-2017-152156  731.940        Furniture
2      Claire Gute   Consumer  CA-2018-164098   18.160  Office Supplies
3      Claire Gute   Consumer  US-2016-123918    5.344  Office Supplies
4      Claire Gute   Consumer  US-2016-123918  131.376        Furniture
5  Darrin Van Huff  Corporate  CA-2017-106656    4.080  Office Supplies
6  Darrin Van Huff  Corporate  CA-2017-106656   18.900  Office Supplies
7  Darrin Van Huff  Corporate  CA-2017-138688   14.620  Office Supplies
8  Darrin Van Huff  Corporate  CA-2018-125745   19.520        Furniture
9  Darrin Van Huff  Corporate  CA-2018-139773  188.552        Furniture

advanced_sql

sub query

In [24]:
query = """
SELECT
    "Order ID",
    "Product Name",
    Sales
FROM sales
WHERE Sales > (
    SELECT AVG(Sales)
    FROM sales
)
ORDER BY Sales DESC;
"""

pd.read_sql_query(query, conn).head(10)

,Order ID,Product Name,Sales
0,CA-2015-145317,Cisco TelePresence System EX90 Videoconferenci...,22638.480
1,CA-2017-118689,Canon imageCLASS 2200 Advanced Copier,17499.950
2,CA-2018-140151,Canon imageCLASS 2200 Advanced Copier,13999.960
3,CA-2018-127180,Canon imageCLASS 2200 Advanced Copier,11199.968
4,CA-2018-166709,Canon imageCLASS 2200 Advanced Copier,10499.970
5,CA-2017-117121,GBC Ibimaster 500 Manual ProClick Binding System,9892.740
6,CA-2015-116904,Ibico EPK-21 Electric Binding System,9449.950
7,US-2017-107440,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930
8,CA-2017-158841,HP Designjet T520 Inkjet Large Format Printer ...,8749.950
9,CA-2017-143714,Canon imageCLASS 2200 Advanced Copier,8399.976

##CTE_WITH

In [25]:
query = """
WITH product_sales AS (
    SELECT
        "Product Name",
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY "Product Name"
)

SELECT *
FROM product_sales
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

##RANK

In [26]:
query = """
SELECT
    "Product Name",
    Sales,
    RANK() OVER (
        ORDER BY Sales DESC
    ) AS Sales_Rank
FROM sales
LIMIT 20;
"""

pd.read_sql_query(query, conn)

                                         Product Name      Sales  Sales_Rank
0   Cisco TelePresence System EX90 Videoconferenci...  22638.480           1
1               Canon imageCLASS 2200 Advanced Copier  17499.950           2
2               Canon imageCLASS 2200 Advanced Copier  13999.960           3
3               Canon imageCLASS 2200 Advanced Copier  11199.968           4
4               Canon imageCLASS 2200 Advanced Copier  10499.970           5
5    GBC Ibimaster 500 Manual ProClick Binding System   9892.740           6
6                Ibico EPK-21 Electric Binding System   9449.950           7
7    3D Systems Cube Printer, 2nd Generation, Magenta   9099.930           8
8   HP Designjet T520 Inkjet Large Format Printer ...   8749.950           9
9               Canon imageCLASS 2200 Advanced Copier   8399.976          10
10        High Speed Automatic Electric Letter Opener   8187.650          11
11          Lexmark MX611dhe Monochrome Laser Printer   8159.952          12
12          Cubify CubeX 3D Printer Triple Head Print   7999.980          13
13  HP Designjet T520 Inkjet Large Format Printer ...   6999.960          14
14  Fellowes PB500 Electric Punch Plastic Comb Bin...   6354.950          15
15          GBC DocuBind P400 Electric Binding System   5443.960          16
16               Hewlett Packard LaserJet 3310 Copier   5399.910          17
17   3D Systems Cube Printer, 2nd Generation, Magenta   5199.960          18
18  Fellowes PB500 Electric Punch Plastic Comb Bin...   5083.960          19
19        High Speed Automatic Electric Letter Opener   4912.590          20

##ROW

In [27]:
query = """
SELECT
    "Product Name",
    Sales,
    ROW_NUMBER() OVER (
        ORDER BY Sales DESC
    ) AS Row_Number
FROM sales
LIMIT 20;
"""

pd.read_sql_query(query, conn)

                                         Product Name      Sales  Row_Number
0   Cisco TelePresence System EX90 Videoconferenci...  22638.480           1
1               Canon imageCLASS 2200 Advanced Copier  17499.950           2
2               Canon imageCLASS 2200 Advanced Copier  13999.960           3
3               Canon imageCLASS 2200 Advanced Copier  11199.968           4
4               Canon imageCLASS 2200 Advanced Copier  10499.970           5
5    GBC Ibimaster 500 Manual ProClick Binding System   9892.740           6
6                Ibico EPK-21 Electric Binding System   9449.950           7
7    3D Systems Cube Printer, 2nd Generation, Magenta   9099.930           8
8   HP Designjet T520 Inkjet Large Format Printer ...   8749.950           9
9               Canon imageCLASS 2200 Advanced Copier   8399.976          10
10        High Speed Automatic Electric Letter Opener   8187.650          11
11          Lexmark MX611dhe Monochrome Laser Printer   8159.952          12
12          Cubify CubeX 3D Printer Triple Head Print   7999.980          13
13  HP Designjet T520 Inkjet Large Format Printer ...   6999.960          14
14  Fellowes PB500 Electric Punch Plastic Comb Bin...   6354.950          15
15          GBC DocuBind P400 Electric Binding System   5443.960          16
16               Hewlett Packard LaserJet 3310 Copier   5399.910          17
17   3D Systems Cube Printer, 2nd Generation, Magenta   5199.960          18
18  Fellowes PB500 Electric Punch Plastic Comb Bin...   5083.960          19
19        High Speed Automatic Electric Letter Opener   4912.590          20

##LAG

In [28]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Month
)

SELECT
    Month,
    Total_Sales,
    LAG(Total_Sales) OVER (
        ORDER BY Month
    ) AS Previous_Month_Sales
FROM monthly_sales
ORDER BY Month;
"""

pd.read_sql_query(query, conn)

  Month   Total_Sales Previous_Month_Sales
0  None  2.252607e+06                 None

##VIEW

In [29]:
query = """
CREATE VIEW IF NOT EXISTS high_value_sales AS
SELECT
    "Order ID",
    "Customer Name",
    "Product Name",
    Sales
FROM sales
WHERE Sales > 1000;
"""

conn.execute(query)
conn.commit()

print("View created successfully!")

View created successfully!

In [30]:
query = """
SELECT *
FROM high_value_sales
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,Order ID,Customer Name,Product Name,Sales
0,CA-2015-115812,Brosina Hoffman,Chromcraft Rectangular Conference Tables,1706.184
1,CA-2016-106320,Emily Burns,Bretford CR4500 Series Slim Rectangular Table,1044.630
2,US-2016-150630,Tracy Blumstein,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430
3,CA-2017-117590,Gene Hale,GE 30524EE4,1097.544
4,CA-2017-105816,Janet Molinari,AT&T CL83451 4-Handset Telephone,1029.950
5,CA-2015-106376,Brendan Sweed,Hunt BOSTON Model 1606 High-Volume Electric Pe...,1113.024
6,CA-2017-114489,Justin Ellison,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",1951.840
7,CA-2015-139892,Becky Martin,Lexmark MX611dhe Monochrome Laser Printer,8159.952
8,CA-2015-139892,Becky Martin,SAFCO Arco Folding Chair,1740.060
9,CA-2016-146262,Victoria Wilson,Cisco 9971 IP Video Phone Charcoal,1188.000

In [27]:
import pandas as pd
import duckdb

In [29]:
df=pd.read_csv("cleaned_dataset.csv")

In [30]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [32]:
query="""
select*
FROM df
"""
res = duckdb.sql(query).df()
res

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9784,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9785,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9786,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9787,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9788,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [34]:
query1 = """
select Category,state
FROM df
"""
resu = duckdb.sql(query1).df()
resu

             Category       State
0           Furniture    Kentucky
1           Furniture    Kentucky
2     Office Supplies  California
3           Furniture     Florida
4     Office Supplies     Florida
...               ...         ...
9784  Office Supplies    Illinois
9785  Office Supplies        Ohio
9786       Technology        Ohio
9787       Technology        Ohio
9788       Technology        Ohio

[9789 rows x 2 columns]

In [35]:
#1 top 5 products by sales




query2 = """
SELECT *
FROM (
    SELECT 
        "Product ID",
        Category,
        Sales,
        RANK() OVER (
            PARTITION BY Category 
            ORDER BY Sales DESC
        ) AS top_product
    FROM df
) t
WHERE top_product <= 5
ORDER BY Category, top_product
"""

res = duckdb.sql(query2).df()

res

         Product ID         Category      Sales  top_product
0   FUR-CH-10002024        Furniture   4416.174            1
1   FUR-TA-10000198        Furniture   4297.644            2
2   FUR-BO-10004834        Furniture   4228.704            3
3   FUR-BO-10002213        Furniture   4007.840            4
4   FUR-CH-10002024        Furniture   3785.292            5
5   OFF-BI-10000545  Office Supplies   9892.740            1
6   OFF-BI-10001120  Office Supplies   9449.950            2
7   OFF-SU-10000151  Office Supplies   8187.650            3
8   OFF-BI-10003527  Office Supplies   6354.950            4
9   OFF-BI-10004995  Office Supplies   5443.960            5
10  TEC-MA-10002412       Technology  22638.480            1
11  TEC-CO-10004722       Technology  17499.950            2
12  TEC-CO-10004722       Technology  13999.960            3
13  TEC-CO-10004722       Technology  11199.968            4
14  TEC-CO-10004722       Technology  10499.970            5

In [36]:
#2 Top 5 customers by total sales


query = """
SELECT 
    "Customer Name",
    SUM(Sales) AS total_sales
FROM df
GROUP BY "Customer Name"
ORDER BY total_sales DESC
LIMIT 5
"""

res = duckdb.sql(query).df()

res

   Customer Name  total_sales
0    Sean Miller    25043.050
1   Tamara Chand    19052.218
2   Raymond Buch    15117.339
3   Tom Ashbrook    14595.620
4  Adrian Barton    14473.571

In [37]:
#3 TOP 5 PRODUCT BY SALES


query = """ 
select
"Product Name",
sum(sales) as total_sales 
from df 
group by "Product Name"
order by total_sales desc
limit 5
"""

res = duckdb.sql(query).df()
res

                                        Product Name  total_sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

In [38]:
#4 SALES BY REGION


query = """ 
select Region,
sum(sales) as Total_sales 
from df 
group by Region
order by Total_sales DESC
limit 5

"""

res = duckdb.sql(query).df()
res

    Region  Total_sales
0     West  710219.6845
1     East  660589.3560
2  Central  492646.9132
3    South  389151.4590

In [39]:
#5 sales by category 


query = """ 
select Category,
sum(sales) as total_sales 
from df 
group by Category 
order by total_sales desc
limit 5

"""
res = duckdb.sql(query)
res

┌─────────────────┬───────────────────┐
│    Category     │    total_sales    │
│     varchar     │      double       │
├─────────────────┼───────────────────┤
│ Technology      │ 825856.1129999965 │
│ Furniture       │ 723538.4756999997 │
│ Office Supplies │ 703212.8240000032 │
└─────────────────┴───────────────────┘

In [40]:
#7 top 5 sub-categories 


query = """
SELECT 
    "Sub-Category",
    SUM(Sales) AS total_sales
FROM df 
GROUP BY "Sub-Category"
ORDER BY total_sales DESC
LIMIT 5
"""

res = duckdb.sql(query).df()
res

  Sub-Category  total_sales
0       Phones   326487.698
1       Chairs   322107.531
2      Storage   217779.102
3       Tables   202810.628
4      Binders   200028.785

In [41]:
#top 5 product in each category 
query8 = """
SELECT *
FROM (
    SELECT 
        Category,
        "Product Name",
        SUM(Sales) AS total_sales,
        RANK() OVER (
            PARTITION BY Category
            ORDER BY SUM(Sales) DESC
        ) AS product_rank
    FROM df
    GROUP BY Category, "Product Name"
) t
WHERE product_rank <= 5
ORDER BY Category, product_rank
"""

res8 = duckdb.sql(query8).df()

res8

,Category,Product Name,total_sales,product_rank
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.5760,1
1,Furniture,Bretford Rectangular Conference Table Tops,12995.2915,2
2,Furniture,Global Troy Executive Leather Low-Back Tilter,12975.3820,3
3,Furniture,SAFCO Arco Folding Chair,11572.7800,4
4,Furniture,"Riverside Palais Royal Lawyers Bookcase, Royal...",11206.0656,5
5,Office Supplies,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.3840,1
6,Office Supplies,GBC DocuBind TL300 Electric Binding System,19823.4790,2
7,Office Supplies,GBC Ibimaster 500 Manual ProClick Binding System,19024.5000,3
8,Office Supplies,GBC DocuBind P400 Electric Binding System,17965.0680,4
9,Office Supplies,High Speed Automatic Electric Letter Opener,17030.3120,5
10,Technology,Canon imageCLASS 2200 Advanced Copier,61599.8240,1
11,Technology,Cisco TelePresence System EX90 Videoconferenci...,22638.4800,2
12,Technology,Hewlett Packard LaserJet 3310 Copier,18839.6860,3
13,Technology,HP Designjet T520 Inkjet Large Format Printer ...,18374.8950,4
14,Technology,Lexmark MX611dhe Monochrome Laser Printer,16829.9010,5

In [42]:
#top 5 product in each category


query8 = """
SELECT *
FROM (
    SELECT 
        Category,
        "Product Name",
        SUM(Sales) AS total_sales,
        RANK() OVER (
            PARTITION BY Category
            ORDER BY SUM(Sales) DESC
        ) AS product_rank
    FROM df
    GROUP BY Category, "Product Name"
) t
WHERE product_rank <= 5
ORDER BY Category, product_rank
"""

res8 = duckdb.sql(query8).df()

res8

,Category,Product Name,total_sales,product_rank
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.5760,1
1,Furniture,Bretford Rectangular Conference Table Tops,12995.2915,2
2,Furniture,Global Troy Executive Leather Low-Back Tilter,12975.3820,3
3,Furniture,SAFCO Arco Folding Chair,11572.7800,4
4,Furniture,"Riverside Palais Royal Lawyers Bookcase, Royal...",11206.0656,5
5,Office Supplies,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.3840,1
6,Office Supplies,GBC DocuBind TL300 Electric Binding System,19823.4790,2
7,Office Supplies,GBC Ibimaster 500 Manual ProClick Binding System,19024.5000,3
8,Office Supplies,GBC DocuBind P400 Electric Binding System,17965.0680,4
9,Office Supplies,High Speed Automatic Electric Letter Opener,17030.3120,5
10,Technology,Canon imageCLASS 2200 Advanced Copier,61599.8240,1
11,Technology,Cisco TelePresence System EX90 Videoconferenci...,22638.4800,2
12,Technology,Hewlett Packard LaserJet 3310 Copier,18839.6860,3
13,Technology,HP Designjet T520 Inkjet Large Format Printer ...,18374.8950,4
14,Technology,Lexmark MX611dhe Monochrome Laser Printer,16829.9010,5